# Generated by Django 4.1.1 on 2022-10-04 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='globant.hired_employees'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='globant.hired_employees'),
        ),
    ]
