# Generated by Django 4.1.1 on 2022-10-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globant', '0002_alter_departments_id_alter_jobs_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hired_employees',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
